---
info:
  app:
    title: Practice Webapp BFF
    description: BFF for the Practice Webapp.

server:
  port: 8081

services:
  patient-service:
    base-url: http://TODO
  practice-webapp:
    base-url: http://TODO

spring:
  application:
    name: practice-webapp-bff
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 5m
      routes:
        # ============================================================================================================ #
        - id: patient-service
          uri: ${services.patient-service.base-url}
          order: 2
          predicates:
            - Method=GET
            - Path=/api/patients/**
          filters:
            - RewritePath=/api/patients(?<segment>/?.*), /patients$\{segment}
        # ============================================================================================================ #
        - id: practice-webapp
          uri: ${services.practice-webapp.base-url}
          order: 100
          predicates:
            - Method=GET
            - Path=/**
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: select 1
      maximum-pool-size: 10
      minimum-idle: 1
    url: jdbc:postgresql://TODO
  flyway:
    baseline-on-migrate: false
    enabled: true
  jackson:
    default-property-inclusion: non_null
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
  main:
    web-application-type: reactive
