---
logging:
  level:
    org:
      springframework: DEBUG

server:
  port: 8081

services:
  patient-service:
    base-url: http://TODO
  practice-webapp:
    base-url: http://TODO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/practice
    username: practice_webapp_bff_rw
    password: practice_webapp_bff_rw
  flyway:
    url: ${spring.datasource.url}
    baseline-on-migrate: true
    user: practice_webapp_bff_admin
    password: practice_webapp_bff_admin

# Profile for doing local development on the practice webapp
---
spring.config.activate.on-profile: local-practice-webapp

services:
  practice-webapp:
    base-url: http://localhost:8080

# Profile for doing local development on the patient service
---
spring.config.activate.on-profile: local-patient-service

services:
  patient-service:
    base-url: http://localhost:8082
